Repository FE-14/greenpeace-frontend, pull requests merged in 2022-11, with the labels that each got.

#58 Setup the `react` project boilerplate
  .env
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  artikel/index.html
  blog/index.html
  favicon.png
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/vite.svg
  search/index.html
  src/App.jsx
  src/App.test.jsx
  src/app/store.js
  src/assets/css/index.css
  src/assets/index.js
  src/assets/js/artikel.js
  src/assets/js/blog.js
  src/assets/js/index.js
  src/assets/js/modules/createArticleUrl.js
  src/assets/js/modules/createTagElements.js
  src/assets/js/modules/filterArticlesByCategory.js
  src/assets/js/modules/filterArticlesByTitle.js
  src/assets/js/modules/formatPublishedDate.js
  src/assets/js/modules/getArticlePostData.js
  src/assets/js/modules/index.js
  src/assets/js/modules/renderArticleCard.js
  src/assets/js/modules/updateArticleContent.js
  src/assets/js/modules/updateSelectedTagButtons.js
  src/assets/js/modules/useState.js
  src/assets/js/navbar.js
  src/assets/js/navbarSearch.js
  src/assets/js/search.js
  src/assets/react.svg
  src/components/index.js
  src/features/index.js
  src/index.css
  src/main.jsx
  src/routes/index.js
  src/setupTests.js
  tailwind.config.cjs
  vite.config.js
Labels: documentation, enhancement

#62 Setup the `react` project boilerplate
  src/App.test.jsx
Labels: documentation, enhancement

#63 Add json data
  src/data/data.json
Labels: enhancement

#68 Created Homepage
  .env
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/app/store.js
  src/assets/images/article-hero.webp
  src/assets/images/artikel-hero.png
  src/assets/images/greenpeace-indonesia-home.png
  src/assets/images/homepage-hero.webp
  src/assets/index.js
  src/assets/react.svg
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/RootLayout.jsx
  src/components/index.js
  src/features/homepage/homapageSlice.js
  src/features/index.js
  src/features/posts/postsSlice.js
  src/index.css
  src/main.jsx
  src/router.jsx
  src/routes/Root.jsx
  src/routes/article.jsx
  src/routes/articles.jsx
  src/routes/homepage/Homepage.jsx
  src/routes/homepage/components/ActivistDigitalCard.jsx
  src/routes/homepage/components/ArticleDescriptionParagraph.jsx
  src/routes/homepage/components/HomepageArticles.jsx
  src/routes/homepage/components/HomepageSection.jsx
  src/routes/homepage/components/index.js
  src/routes/index.js
  tailwind.config.cjs
Labels: enhancement

#69 Fix bug untuk gambar ilustrasi
  index.html
  public/favicon.png
  public/greenpeace-indonesia-home.png
  src/routes/homepage/Homepage.jsx
Labels: bug

#70 Tambahkan README.md file
  README.md
Labels: documentation

#73 Created Articles page
  package-lock.json
  package.json
  public/_redirects
  src/App.jsx
  src/components/ArticleCard.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/ReadMoreArticleLink.jsx
  src/components/RootLayout.jsx
  src/components/index.js
  src/index.css
  src/libs/formatPublishedDate.js
  src/libs/getPostData.js
  src/libs/index.js
  src/router.jsx
  src/routes/Article.jsx
  src/routes/Error.jsx
  src/routes/articles.jsx
  src/routes/articles/Articles.jsx
  src/routes/articles/components/ArticlesList.jsx
  src/routes/articles/components/ButtonCategory.jsx
  src/routes/articles/components/SearchArticleBar.jsx
  src/routes/articles/components/SkeletonArticles.jsx
  src/routes/articles/components/index.js
  src/routes/homepage/Homepage.jsx
  src/routes/homepage/components/ActivistDigitalCard.jsx
  src/routes/homepage/components/HomepageArticles.jsx
  src/routes/index.js
Labels: enhancement

#76 Create detail article page
  package-lock.json
  package.json
  src/components/Navbar.jsx
  src/libs/getDetailPostData.js
  src/libs/getPostData.js
  src/libs/index.js
  src/main.jsx
  src/router.jsx
  src/routes/Article.jsx
  src/routes/articles/Articles.jsx
  src/routes/detail-article/DetailArticle.jsx
  src/routes/detail-article/components/Article.jsx
  src/routes/detail-article/components/ArticleTag.jsx
  src/routes/detail-article/components/DetailArticleSkeleton.jsx
  src/routes/detail-article/components/index.js
  src/routes/index.js
Labels: enhancement

#77 Created search page
  src/app/store.js
  src/components/Navbar.jsx
  src/components/SkeletonArticles.jsx
  src/components/index.js
  src/features/search/searchSlice.js
  src/index.css
  src/router.jsx
  src/routes/Search.jsx
  src/routes/articles/Articles.jsx
  src/routes/articles/components/ArticlesList.jsx
  src/routes/articles/components/index.js
  src/routes/index.js
Labels: enhancement

#84 Update search field on search page
  src/components/Navbar.jsx
  src/routes/Search.jsx
Labels: enhancement

#86 Create intro about on homepage
  src/assets/images/bg-intro-about-1.png
  src/assets/images/bg-intro-about-2.png
  src/assets/index.js
  src/routes/homepage/Homepage.jsx
  src/routes/homepage/components/HomepageSection.jsx
Labels: enhancement

#90 Update navbar contents
  src/components/navbar/Navbar.jsx
  src/components/navbar/components/DropdownItem.jsx
  src/components/navbar/components/NavbarDropdown.jsx
  src/components/navbar/components/SearchBar.jsx
Labels: enhancement

#95 Update and fix footer
  src/components/Footer.jsx
Labels: enhancement

#94 Create sejarah page
  src/assets/images/about-logo.png
  src/assets/images/artboard-rectangle.png
  src/assets/images/history-logo.png
  src/assets/images/victory-logo.png
  src/assets/index.js
  src/components/Footer.jsx
  src/components/SectionGpCard.jsx
  src/components/index.js
  src/routes/history/History.jsx
  src/routes/homepage/Homepage.jsx
Labels: enhancement

#96 Create about page
  src/components/RootLayout.jsx
  src/router.jsx
  src/routes/about/About.jsx
  src/routes/about/components/AboutSection.jsx
  src/routes/about/components/ArticleList.jsx
  src/routes/about/components/index.js
  src/routes/detail-article/DetailArticle.jsx
  src/routes/index.js
Labels: enhancement

#98 Membuat halaman `Kemenangan`
  index.html
  public/greenpeace-indonesia-about.webp
  public/greenpeace-indonesia-articles.webp
  public/greenpeace-indonesia-history.webp
  public/greenpeace-indonesia-home.png
  public/greenpeace-indonesia-home.webp
  public/greenpeace-indonesia-our-victory.webp
  src/App.jsx
  src/assets/images/artboard-rectangle.png
  src/assets/images/artboard-rectangle.webp
  src/assets/images/article-hero.webp
  src/assets/images/bg-intro-about-1.png
  src/assets/images/bg-intro-about-1.webp
  src/assets/images/bg-intro-about-2.png
  src/assets/images/bg-intro-about-2.webp
  src/assets/images/green-big-outline-half-artboard.png
  src/assets/images/green-big-outline-half-artboard.webp
  src/assets/images/green-full-artboard.png
  src/assets/images/green-full-artboard.webp
  src/assets/images/green-line-illustration.png
  src/assets/images/green-line-illustration.webp
  src/assets/images/green-outline-half-artboard.png
  src/assets/images/green-outline-half-artboard.webp
  src/assets/images/history-cover.png
  src/assets/images/history-cover.webp
  src/assets/images/homepage-hero.webp
  src/assets/images/our-victory-cover.webp
  src/assets/index.js
  src/router.jsx
  src/routes/about/About.jsx
  src/routes/articles/Articles.jsx
  src/routes/detail-article/DetailArticle.jsx
  src/routes/history/History.jsx
  src/routes/homepage/Homepage.jsx
  src/routes/index.js
  src/routes/our-victory/OurVictory.jsx
  src/routes/our-victory/components/Accordion.jsx
  src/routes/our-victory/components/AccordionItem.jsx
  src/routes/our-victory/components/index.js
  tailwind.config.cjs
Labels: enhancement
