Repository FE-14/greenpeace-frontend, pull requests merged in 2022-10, with the labels that each got.

#10 Feat : update README.md
  README.md
Labels: documentation

#16 Collect resources
  README.md
  src/data/data.json
Labels: documentation, duplicate, enhancement

#26 feat menyelesaikan tampilan beranda
  .gitignore
  index.html
Labels: enhancement

#27 feat article page
  README.md
  artikel/index.html
  package.json
  src/assets/js/artikel.js
  src/assets/js/modules/createArticleUrl.js
  src/assets/js/modules/formatPublishedDate.js
  src/assets/js/modules/index.js
  src/assets/js/modules/renderArticleCard.js
  src/assets/js/modules/updateArticleContent.js
Labels: enhancement

#28 Feat blog page
  blog/index.html
  src/assets/js/blog.js
  src/assets/js/modules/createTagElements.js
  src/assets/js/modules/index.js
Labels: enhancement

#29 Update documentation
  .gitignore
  README.md
  artikel/index.html
  index.html
  package.json
  src/assets/js/artikel.js
  src/assets/js/index.js
  src/assets/js/modules/createArticleUrl.js
  src/assets/js/modules/formatPublishedDate.js
  src/assets/js/modules/getArticlePostData.js
  src/assets/js/modules/index.js
  src/assets/js/modules/renderArticleCard.js
  src/assets/js/modules/updateArticleContent.js
  src/assets/js/modules/useState.js
  src/data/data.json
  tailwind.config.js
Labels: documentation

#30 menambahkan nama bekalang meilyana
  README.md
  artikel/index.html
Labels: documentation

#31 Update README.md
  README.md
Labels: documentation

#33 18 create articles page
  artikel/index.html
  blog/index.html
  index.html
Labels: enhancement

#34 Update blog page
  artikel/index.html
  blog/index.html
  index.html
  src/assets/js/blog.js
Labels: enhancement

#38 feat: memperbarui halaman beranda, artikel, dan blog
  .gitignore
  .vscode/settings.json
  README.md
  artikel/index.html
  blog/index.html
  index.html
  package.json
  src/assets/js/artikel.js
  src/assets/js/blog.js
  src/assets/js/index.js
  src/assets/js/modules/createArticleUrl.js
  src/assets/js/modules/createTagElements.js
  src/assets/js/modules/formatPublishedDate.js
  src/assets/js/modules/getArticlePostData.js
  src/assets/js/modules/index.js
  src/assets/js/modules/renderArticleCard.js
  src/assets/js/modules/updateArticleContent.js
  src/assets/js/modules/useState.js
  src/data/data.json
  tailwind.config.js
Labels: bug, documentation, enhancement

#46 Created a search functionality and selected category in article page
  artikel/index.html
  blog/index.html
  index.html
  src/assets/js/artikel.js
  src/assets/js/index.js
  src/assets/js/modules/filterArticlesByCategory.js
  src/assets/js/modules/filterArticlesByTitle.js
  src/assets/js/modules/index.js
  src/assets/js/modules/renderArticleCard.js
  src/assets/js/modules/updateSelectedTagButtons.js
  src/assets/js/navbar.js
  tailwind.config.js
Labels: enhancement
